// SERVER-ONLY data access. Importing this module pulls the full 9.4MB
// lectures.json into the bundle — client components must use
// lib/lecture-utils.ts (types/helpers) and lib/client-catalog.ts (data,
// fetched lazily from /lectures-data/catalog.json) instead.

import { readFileSync } from 'fs'
import { join } from 'path'
import lecturesData from '@/data/lectures.json'
import type { Lecture, TreeNode, FlatLecture } from '@/lib/lecture-utils'

export type { Lecture, TreeNode, FlatLecture }
export { formatDuration } from '@/lib/lecture-utils'

export const categories: TreeNode[] = lecturesData.categories as TreeNode[]

// ─── Recursive helpers ────────────────────────────────────────────────────────

export function flattenLectures(
  node: TreeNode,
  breadcrumb: string[] = []
): FlatLecture[] {
  const crumb = [...breadcrumb, node.label]
  const results: FlatLecture[] = []
  if (node.lectures) {
    results.push(...node.lectures.map(lec => ({ ...lec, breadcrumb: crumb, nodeId: node.id })))
  }
  if (node.children) {
    results.push(...node.children.flatMap(child => flattenLectures(child, crumb)))
  }
  return results
}

/**
 * All lectures across every category, flattened. Used for search, the lecture
 * detail page, and adjacent-lecture lookups.
 *
 * Reads public/lectures-data/catalog.json — generated by generate-node-data.mjs
 * at build time — rather than re-deriving from the static `categories` import
 * above. Unlike `categories` (a direct bundle of data/lectures.json, which never
 * changes between deploys), catalog.json has active Supabase `pending_lectures`
 * merged in, so newly-ingested shiurim resolve here instead of 404ing. Falls
 * back to deriving from `categories` if the generated file isn't present yet
 * (e.g. a context that never ran the generate step).
 */
let _allLectures: FlatLecture[] | null = null
export function getAllLectures(): FlatLecture[] {
  if (_allLectures) return _allLectures
  try {
    const raw = readFileSync(join(process.cwd(), 'public', 'lectures-data', 'catalog.json'), 'utf8')
    _allLectures = JSON.parse(raw) as FlatLecture[]
  } catch {
    const seen = new Set<string>()
    _allLectures = categories
      .flatMap(cat => flattenLectures(cat))
      .filter(l => {
        if (seen.has(l.id)) return false
        seen.add(l.id)
        return true
      })
  }
  return _allLectures
}

/** Find a single lecture by id anywhere in the tree. */
export function getLectureById(id: string): FlatLecture | null {
  return getAllLectures().find(l => l.id === id) ?? null
}

/** Find the TreeNode at a given path of ids, e.g. ["chumash","bereishit","noach"] */
export function getNodeByPath(path: string[]): TreeNode | null {
  if (!path.length) return null
  let node: TreeNode | undefined = categories.find(c => c.id === path[0])
  for (let i = 1; i < path.length; i++) {
    node = node?.children?.find(c => c.id === path[i])
  }
  return node ?? null
}

/** Get the path of ids from root to a given node id (breadth-first search). */
export function getPathToNode(targetId: string): string[] | null {
  function search(node: TreeNode, path: string[]): string[] | null {
    const current = [...path, node.id]
    if (node.id === targetId) return current
    for (const child of node.children ?? []) {
      const result = search(child, current)
      if (result) return result
    }
    return null
  }
  for (const cat of categories) {
    const result = search(cat, [])
    if (result) return result
  }
  return null
}

/** Get prev/next lecture in flattened order. */
export function getAdjacentLectures(lectureId: string) {
  const all = getAllLectures()
  const idx = all.findIndex(l => l.id === lectureId)
  return {
    prev: idx > 0 ? all[idx - 1] : null,
    next: idx < all.length - 1 ? all[idx + 1] : null,
  }
}
